name: 'SnykTestProject'
description: 'Playing around'
inputs:
  myToken:
    description: 'GH token'
    required: true
    default: ''
  sourceFilename:
    description: 'Name of the "source" file where Snyk fixes have been injected'
    required: false
    default: 'requirements.txt'
  targetFilename:
    description: 'Name of the "target" file where Snyk fixes will be propagated to'
    required: false
    default: 'requirements.in'
  branchPattern:
    description: 'Branch pattern for which this logic should kick in'
    required: false
    default: 'snyk-fix-'
outputs:
runs:
  using: 'node12'
  main: 'dist/index.js'
