version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    setup:
        executor:
        name: node/default
        steps:
            - checkout
            - run:
                name: "Setup Snyk"
                command: |
                    npm install -g snyk
    build:
        executor:
        name: node/default
        steps:
            - run: npm install
    test:
        executor:
        name: node/default
        steps:
            - checkout
            - run: npm test
            - run:
                name: "Snyk Test"
                command: |
                    snyk test --org=customer-facing-tools
    monitor:
        executor:
        name: node/default
        steps:
            - run:
                name: "Snyk Monitor"
                command: |
                    snyk monitor --org=customer-facing-tools
            - run: tsc
    compile:
        executor:
        name: node/default
        steps:
            - run: tsc
workflows:
    build-and-test:
      jobs:
        - setup
        - build
        - test      
        - compile
        - monitor