version: 2.1
orbs:
  node: circleci/node@1.1.6

workflows:
    build-and-test:
        jobs:
            - setup:
                steps:
                    - checkout
                    - run:
                        name: "Setup Snyk"
                        command: |
                            npm install -g snyk
            - build:
                steps:
                    - run: npm install
            - test:
                steps:
                    - checkout
                    - run: npm test
                    - run:
                        name: "Snyk Test"
                        command: |
                            snyk test --org=customer-facing-tools
            - monitor:
                steps:
                    - run:
                        name: "Snyk Monitor"
                        command: |
                            snyk monitor --org=customer-facing-tools
                    - run: tsc
            - compile:
                steps:
                    - run: tsc